<div class="space-y-6">
    <!-- Report Official Header -->
    <div class="flex items-center justify-between pb-8 border-b-2 border-gray-900 mb-8">
        <div class="flex items-center gap-4">
            <div class="w-12 h-12 bg-gray-900 rounded-xl flex items-center justify-center text-white shadow-lg">
                <svg class="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M4 6h16M4 10h16M4 14h16M4 18h16" />
                </svg>
            </div>
            <div>
                <h1 class="text-xl font-black uppercase tracking-widest text-gray-900">Alumni Dataset Registry</h1>
                <p class="text-[9px] font-bold text-gray-400 uppercase tracking-[0.2em] mt-0.5">Raw Professional
                    Intelligence • {{ $data->count() }} Records</p>
            </div>
        </div>
        <div class="text-right">
            <p class="text-[9px] font-black text-gray-400 uppercase tracking-widest leading-tight">Generated by:
                {{ Auth::user()->name }}</p>
            <p class="text-[9px] font-black text-brand-600 uppercase tracking-widest mt-1">{{ date('F d, Y • H:i') }}
            </p>
        </div>
    </div>

    @if($data->isEmpty())
        <div class="bg-white p-16 rounded-[3rem] border border-gray-100 shadow-sm text-center">
            <div class="w-20 h-20 bg-gray-50 text-gray-400 rounded-full flex items-center justify-center mx-auto mb-6">
                <svg class="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4" />
                </svg>
            </div>
            <p class="text-lg font-black text-gray-900 uppercase tracking-tighter">No Matches Found</p>
            <p class="text-[10px] font-bold text-gray-400 uppercase tracking-widest mt-2">Try adjusting your filters to
                broaden your search.</p>
        </div>
    @else
        <div class="bg-white rounded-[2.5rem] border border-gray-100 shadow-sm overflow-hidden">
            <div class="overflow-x-auto">
                <table class="w-full text-left">
                    <thead>
                        <tr class="bg-gray-50/50 border-b border-gray-100">
                            <th class="px-6 py-5 text-[10px] font-black text-gray-400 uppercase tracking-widest">Alumni Name
                            </th>
                            <th class="px-6 py-5 text-[10px] font-black text-gray-400 uppercase tracking-widest">Program
                            </th>
                            <th class="px-6 py-5 text-[10px] font-black text-gray-400 uppercase tracking-widest">Batch</th>
                            <th class="px-6 py-5 text-[10px] font-black text-gray-400 uppercase tracking-widest">Work Status
                            </th>
                            <th class="px-6 py-5 text-[10px] font-black text-gray-400 uppercase tracking-widest">Employment
                            </th>
                            <th class="px-6 py-5 text-[10px] font-black text-gray-400 uppercase tracking-widest">Location
                            </th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-50">
                        @foreach($data as $alumnus)
                            <tr class="hover:bg-gray-50/50 transition-colors group">
                                <td class="px-6 py-5">
                                    <div class="font-black text-gray-900 uppercase text-[11px]">{{ $alumnus->full_name }}</div>
                                </td>
                                <td class="px-6 py-5">
                                    <span
                                        class="px-3 py-1 bg-brand-50 text-brand-700 rounded-full text-[9px] font-black uppercase">{{ $alumnus->course->code }}</span>
                                </td>
                                <td class="px-6 py-5">
                                    <span class="font-bold text-gray-500 text-[11px]">{{ $alumnus->batch_year }}</span>
                                </td>
                                <td class="px-6 py-5">
                                    <div class="flex items-center gap-2">
                                        <div
                                            class="w-1.5 h-1.5 rounded-full {{ $alumnus->employment_status === 'Employed' ? 'bg-green-500' : 'bg-gray-300' }}">
                                        </div>
                                        <span
                                            class="font-black text-gray-900 uppercase text-[10px]">{{ $alumnus->employment_status }}</span>
                                    </div>
                                </td>
                                <td class="px-6 py-5">
                                    <div class="text-[10px] font-bold text-gray-900">{{ $alumnus->work_status ?? 'N/A' }}</div>
                                    <div class="text-[9px] text-gray-400 uppercase font-bold">
                                        {{ $alumnus->establishment_type ?? '-' }}
                                    </div>
                                </td>
                                <td class="px-6 py-5">
                                    <span
                                        class="px-3 py-1 border border-gray-200 rounded-full text-[9px] font-black uppercase text-gray-600">{{ $alumnus->work_location ?? 'N/A' }}</span>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    @endif
</div>