@php
    $summary = data_get($data, 'summary', [
        'total_count' => 0,
        'employment_rate' => 0,
        'overseas_rate' => 0,
        'dominant_field' => 'N/A',
        'integrity_score' => 0
    ]);
@endphp

<div class="space-y-8" x-data="{ subTab: 'all' }">
    <!-- Report Official Header -->
    <div
        class="flex flex-col sm:flex-row sm:items-center justify-between gap-6 pb-8 border-b-2 border-gray-900 dark:border-dark-border mb-8 text-center sm:text-left">
        <div class="flex flex-col sm:flex-row items-center gap-4">
            <div
                class="w-12 h-12 bg-brand-600 rounded-xl flex items-center justify-center text-white shadow-lg shrink-0">
                <svg class="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
                </svg>
            </div>
            <div>
                <h1 class="text-xl font-black uppercase tracking-widest text-gray-900 dark:text-dark-text-primary">
                    Institutional Analytics</h1>
                <p
                    class="text-[9px] font-bold text-gray-400 dark:text-dark-text-muted uppercase tracking-[0.2em] mt-0.5">
                    Official Employment & Registration Metrics</p>
            </div>
        </div>
        <div class="flex flex-col sm:text-right border-t sm:border-t-0 pt-4 sm:pt-0 dark:border-dark-border">
            <p
                class="text-[9px] font-black text-gray-400 dark:text-dark-text-muted uppercase tracking-widest leading-tight">
                Generated by: {{ Auth::user()->name }}
            </p>
            <p class="text-[9px] font-black text-brand-600 uppercase tracking-widest mt-1">{{ date('F d, Y • H:i') }}
            </p>
        </div>
    </div>

    <!-- Summary KPI Strip -->
    <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-3 sm:gap-4 animate-in fade-in duration-700">
        <div
            class="bg-white dark:bg-dark-bg-elevated p-4 sm:p-6 rounded-[1.5rem] sm:rounded-[2rem] border border-gray-100 dark:border-dark-border shadow-sm flex flex-col justify-center">
            <p class="text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1">Total Verified</p>
            <p class="text-xl sm:text-2xl font-black text-gray-900 dark:text-dark-text-primary">
                {{ number_format(data_get($summary, 'total_count', 0)) }}
            </p>
        </div>
        <div
            class="bg-white dark:bg-dark-bg-elevated p-4 sm:p-6 rounded-[1.5rem] sm:rounded-[2rem] border border-gray-100 dark:border-dark-border shadow-sm flex flex-col justify-center">
            <p class="text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1">Employed Rate</p>
            <p class="text-xl sm:text-2xl font-black text-brand-600">{{ data_get($summary, 'employment_rate', 0) }}%</p>
        </div>
        <div
            class="bg-white dark:bg-dark-bg-elevated p-4 sm:p-6 rounded-[1.5rem] sm:rounded-[2rem] border border-gray-100 dark:border-dark-border shadow-sm flex flex-col justify-center">
            <p class="text-[9px] font-black text-gray-400 uppercase tracking-widest mb-1">Global Reach</p>
            <p class="text-xl sm:text-2xl font-black text-blue-600">{{ data_get($summary, 'overseas_rate', 0) }}%</p>
        </div>
        <div
            class="bg-white dark:bg-dark-bg-elevated p-4 sm:p-6 rounded-[1.5rem] sm:rounded-[2rem] border border-gray-100 dark:border-dark-border shadow-sm">
            <p class="text-[9px] font-black text-gray-400 dark:text-dark-text-muted uppercase tracking-widest mb-1">Top
                Field</p>
            <p class="text-base sm:text-lg font-black text-gray-900 dark:text-dark-text-primary truncate">
                {{ data_get($summary, 'dominant_field', 'N/A') }}
            </p>
        </div>
        <div
            class="bg-white dark:bg-dark-bg-elevated p-4 sm:p-6 rounded-[1.5rem] sm:rounded-[2rem] border border-gray-100 dark:border-dark-border shadow-sm">
            <p class="text-[9px] font-black text-gray-400 dark:text-dark-text-muted uppercase tracking-widest mb-1">
                Data Integrity</p>
            <div class="flex items-end gap-2">
                <p
                    class="text-xl sm:text-2xl font-black {{ $summary['integrity_score'] > 80 ? 'text-green-600' : 'text-amber-500' }}">
                    {{ data_get($summary, 'integrity_score', 0) }}%
                </p>
            </div>
        </div>
    </div>

    <!-- Visual Intelligence Controls -->
    <div
        class="flex flex-wrap items-center justify-between gap-4 border-b border-gray-100 dark:border-dark-border pb-4 no-print">
        <div class="flex bg-gray-100 dark:bg-dark-bg-subtle p-1 rounded-2xl w-full md:w-auto">
            <button @click="subTab = 'all'"
                :class="subTab === 'all' ? 'bg-indigo-600 text-white shadow-lg' : 'text-gray-500 dark:text-dark-text-muted hover:text-gray-700 dark:hover:text-dark-text-secondary'"
                class="flex-1 md:flex-none px-6 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all">Combined
                Matrix</button>
            <button @click="subTab = 'program'"
                :class="subTab === 'program' ? 'bg-brand-600 text-white shadow-lg' : 'text-gray-500 dark:text-dark-text-muted hover:text-gray-700 dark:hover:text-dark-text-secondary'"
                class="flex-1 md:flex-none px-6 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all">Program
                Insights</button>
            <button @click="subTab = 'labor'"
                :class="subTab === 'labor' ? 'bg-purple-600 text-white shadow-lg' : 'text-gray-500 dark:text-dark-text-muted hover:text-gray-700 dark:hover:text-dark-text-secondary'"
                class="flex-1 md:flex-none px-6 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all">Labor
                Analytics</button>
            <button @click="subTab = 'demographics'"
                :class="subTab === 'demographics' ? 'bg-amber-600 text-white shadow-lg' : 'text-gray-500 dark:text-dark-text-muted hover:text-gray-700 dark:hover:text-dark-text-secondary'"
                class="flex-1 md:flex-none px-6 py-2 rounded-xl text-[10px] font-black uppercase tracking-widest transition-all">Demographics</button>
        </div>
        <div class="text-[9px] font-bold text-gray-400 uppercase hidden lg:block italic">💡 Click a tab to focus on
            specific datasets • Report Date: {{ date('M d, Y') }}</div>
    </div>

    <!-- COMBINED MATRIX VIEW -->
    <div x-show="subTab === 'all'" class="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <!-- Top Row Demos -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <!-- Course Dist (Doughnut) -->
            <div
                class="bg-gray-50/50 dark:bg-dark-bg-subtle/50 p-6 rounded-[2rem] border border-gray-100 dark:border-dark-border flex flex-col items-center">
                <span
                    class="text-[9px] font-black text-gray-400 dark:text-dark-text-muted uppercase tracking-widest mb-4">Program
                    vs Labor</span>
                <div class="h-32 w-32 relative">
                    <canvas id="chartByCourse"
                        data-labels="{{ json_encode(collect(data_get($data, 'by_course'))->pluck('code')) }}"
                        data-employed="{{ json_encode(collect(data_get($data, 'by_course'))->pluck('employed')) }}"
                        data-unemployed="{{ json_encode(collect(data_get($data, 'by_course'))->pluck('unemployed')) }}"></canvas>
                </div>
                <div class="mt-4 text-[8px] font-bold text-gray-400 uppercase">Employed vs Unemployed</div>
            </div>

            <!-- Employment (Pie) -->
            <div
                class="bg-gray-50/50 dark:bg-dark-bg-subtle/50 p-6 rounded-[2rem] border border-gray-100 dark:border-dark-border flex flex-col items-center">
                <span
                    class="text-[9px] font-black text-gray-400 dark:text-dark-text-muted uppercase tracking-widest mb-4">Labor
                    Status</span>
                <div class="h-32 w-32 relative">
                    <canvas id="chartByEmployment"
                        data-labels="{{ json_encode(collect(data_get($data, 'by_employment'))->pluck('employment_status')) }}"
                        data-values="{{ json_encode(collect(data_get($data, 'by_employment'))->pluck('count')) }}"></canvas>
                </div>
                <div class="mt-4 text-[8px] font-bold text-gray-400 uppercase">Current Employment</div>
            </div>

            <!-- Gender (Polar Area) -->
            <div
                class="bg-gray-50/50 dark:bg-dark-bg-subtle/50 p-6 rounded-[2rem] border border-gray-100 dark:border-dark-border flex flex-col items-center">
                <span
                    class="text-[9px] font-black text-gray-400 dark:text-dark-text-muted uppercase tracking-widest mb-4">Gender
                    Profile</span>
                <div class="h-32 w-32 relative">
                    <canvas id="chartByGender" data-labels="{{ json_encode($data['by_gender']->pluck('gender')) }}"
                        data-values="{{ json_encode($data['by_gender']->pluck('count')) }}"></canvas>
                </div>
                <div class="mt-4 text-[8px] font-bold text-gray-400 uppercase">Demographic Identity</div>
            </div>

            <!-- Civil Status (Bar) -->
            <div
                class="bg-gray-50/50 dark:bg-dark-bg-subtle/50 p-6 rounded-[2rem] border border-gray-100 dark:border-dark-border flex flex-col items-center">
                <span
                    class="text-[9px] font-black text-gray-400 dark:text-dark-text-muted uppercase tracking-widest mb-4">Stability
                    Focus</span>
                <div class="h-32 w-32 relative">
                    <canvas id="chartStabilityStacked"
                        data-labels="{{ json_encode(collect(data_get($data, 'stability_matrix'))->pluck('program')) }}"
                        data-permanent="{{ json_encode(collect(data_get($data, 'stability_matrix'))->pluck('Permanent')) }}"
                        data-contractual="{{ json_encode(collect(data_get($data, 'stability_matrix'))->pluck('Contractual')) }}"
                        data-jo="{{ json_encode(collect(data_get($data, 'stability_matrix'))->pluck('Job Order')) }}"></canvas>
                </div>
                <div class="mt-4 text-[8px] font-bold text-gray-400 uppercase">Stacked Status Matrix</div>
            </div>
        </div>

        <!-- Momentum Trend (Combination Chart) -->
        <div class="bg-gray-900 dark:bg-dark-bg-deep p-8 rounded-[2.5rem] shadow-2xl">
            <h4 class="text-[9px] font-black text-brand-400 uppercase tracking-widest mb-6 px-2">Overall Employment Flux
                (Combination)</h4>
            <div class="h-48 w-full">
                <canvas id="chartCombinationSummary"
                    data-labels="{{ json_encode(collect(data_get($data, 'combination_data'))->pluck('month')) }}"
                    data-total="{{ json_encode(collect(data_get($data, 'combination_data'))->pluck('total_registrants')) }}"
                    data-employed="{{ json_encode(collect(data_get($data, 'combination_data'))->pluck('employed_count')) }}"></canvas>
            </div>
        </div>
    </div>

    <!-- PROGRAM INSIGHTS FOCUS -->
    <div x-show="subTab === 'program'" class="animate-in fade-in duration-500 space-y-8" x-data="{ 
            page: 1, 
            perPage: 10,
            get totalPages() { return Math.ceil({{ count(data_get($data, 'by_course', [])) }} / this.perPage) },
            get paginatedData() {
                const data = {{ json_encode(data_get($data, 'by_course', [])) }};
                return data.slice((this.page - 1) * this.perPage, this.page * this.perPage);
            }
        }">
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div
                class="lg:col-span-2 bg-white dark:bg-dark-bg-elevated p-8 rounded-[2.5rem] border border-gray-100 dark:border-dark-border shadow-sm">
                <div class="flex items-center justify-between mb-8">
                    <h4 class="text-sm font-black text-gray-900 dark:text-dark-text-primary uppercase tracking-tight">
                        Program Performance Registry
                    </h4>
                    <span
                        class="text-[9px] font-black text-brand-600 bg-brand-50 dark:bg-brand-900/30 px-3 py-1 rounded-full uppercase">
                        {{ count(data_get($data, 'by_course', [])) }} Courses
                    </span>
                </div>

                <div class="overflow-x-auto">
                    <table class="w-full text-left border-separate border-spacing-y-2">
                        <thead>
                            <tr class="text-[9px] font-black text-gray-400 uppercase tracking-widest">
                                <th class="px-4 py-2">Program Code</th>
                                <th class="px-4 py-2 text-center">Registrants</th>
                                <th class="px-4 py-2 text-center">Employed</th>
                                <th class="px-4 py-2 text-center">Health</th>
                            </tr>
                        </thead>
                        <tbody class="text-[11px]">
                            <template x-for="course in paginatedData" :key="course.code">
                                <tr
                                    class="bg-gray-50/50 dark:bg-dark-bg-subtle/50 hover:bg-gray-100 dark:hover:bg-dark-state-hover transition-colors">
                                    <td class="px-4 py-4 rounded-l-2xl">
                                        <div class="font-black text-gray-900 dark:text-dark-text-primary uppercase"
                                            x-text="course.code"></div>
                                        <div class="text-[8px] text-gray-400 font-bold truncate max-w-[150px]"
                                            x-text="course.name"></div>
                                    </td>
                                    <td class="px-4 py-4 text-center font-black text-gray-600 dark:text-dark-text-secondary"
                                        x-text="course.alumni_count"></td>
                                    <td class="px-4 py-4 text-center font-black text-green-600"
                                        x-text="course.employed"></td>
                                    <td class="px-4 py-4 rounded-r-2xl text-center">
                                        <span
                                            class="inline-block px-2 py-0.5 rounded-full text-[8px] font-black uppercase"
                                            :class="course.alumni_count > 0 && (course.employed / course.alumni_count) > 0.7 ? 'bg-green-100 text-green-700' : 'bg-amber-100 text-amber-700'"
                                            x-text="course.alumni_count > 0 ? Math.round((course.employed / course.alumni_count) * 100) + '%' : '0%'">
                                        </span>
                                    </td>
                                </tr>
                            </template>
                        </tbody>
                    </table>
                </div>

                <div class="mt-6 flex items-center justify-between" x-show="totalPages > 1">
                    <button @click="page--" :disabled="page === 1"
                        class="p-2 rounded-xl hover:bg-gray-100 dark:hover:bg-dark-state-hover disabled:opacity-30 disabled:cursor-not-allowed transition-all">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 19l-7-7 7-7" />
                        </svg>
                    </button>
                    <span class="text-[10px] font-black text-gray-400 uppercase tracking-widest">
                        Page <span class="text-gray-900 dark:text-dark-text-primary" x-text="page"></span> of <span
                            x-text="totalPages"></span>
                    </span>
                    <button @click="page++" :disabled="page === totalPages"
                        class="p-2 rounded-xl hover:bg-gray-100 dark:hover:bg-dark-state-hover disabled:opacity-30 disabled:cursor-not-allowed transition-all">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                        </svg>
                    </button>
                </div>
            </div>

            <div class="space-y-4">
                <div
                    class="bg-brand-600 p-8 rounded-[2rem] text-white shadow-xl shadow-brand-100 dark:shadow-none relative overflow-hidden group">
                    <div
                        class="absolute -right-4 -bottom-4 opacity-10 group-hover:scale-110 transition-transform duration-700">
                        <svg class="w-32 h-32" fill="currentColor" viewBox="0 0 24 24">
                            <path
                                d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" />
                        </svg>
                    </div>
                    <p class="text-[9px] font-bold uppercase tracking-[0.2em] opacity-80 mb-2">Flagship Program</p>
                    <h5 class="text-2xl font-black uppercase leading-tight">
                        {{ data_get($data, 'by_course.0.name', 'N/A') }}
                    </h5>
                    <div class="mt-4 pt-4 border-t border-white/20 flex gap-4">
                        <div>
                            <p class="text-[8px] font-bold uppercase opacity-60">Registrants</p>
                            <p class="text-lg font-black">{{ data_get($data, 'by_course.0.alumni_count', 0) }}</p>
                        </div>
                        <div>
                            <p class="text-[8px] font-bold uppercase opacity-60">Success Rate</p>
                            @php
                                $top = data_get($data, 'by_course.0');
                                $topRate = $top && $top['alumni_count'] > 0 ? round(($top['employed'] / $top['alumni_count']) * 100) : 0;
                            @endphp
                            <p class="text-lg font-black">{{ $topRate }}%</p>
                        </div>
                    </div>
                </div>

                <div
                    class="bg-white dark:bg-dark-bg-elevated p-8 rounded-[2rem] border border-gray-100 dark:border-dark-border shadow-sm">
                    <h5
                        class="text-[9px] font-black text-gray-400 dark:text-dark-text-muted uppercase tracking-widest mb-6">
                        Batch Volumetrics
                    </h5>
                    <div class="space-y-4">
                        @foreach(data_get($data, 'by_batch', [])->sortByDesc('batch_year')->take(5) as $batch)
                            <div class="flex items-center gap-4">
                                <div
                                    class="w-10 h-10 bg-gray-50 dark:bg-dark-bg-subtle rounded-xl flex items-center justify-center text-[10px] font-black text-gray-900 dark:text-dark-text-primary">
                                    '{{ substr($batch->batch_year, -2) }}
                                </div>
                                <div class="flex-1">
                                    <div class="flex justify-between items-center mb-1">
                                        <span class="text-[10px] font-bold text-gray-500 uppercase">Class of
                                            {{ $batch->batch_year }}</span>
                                        <span
                                            class="text-[10px] font-black text-gray-900 dark:text-dark-text-primary">{{ $batch->count }}
                                        </span>
                                    </div>
                                    <div
                                        class="w-full bg-gray-100 dark:bg-dark-bg-subtle h-1.5 rounded-full overflow-hidden">
                                        <div class="bg-brand-500 h-full rounded-full"
                                            style="width: {{ min(100, ($batch->count / max(1, data_get($summary, 'total_count', 1))) * 500) }}%">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>

        <div class="bg-gray-900 dark:bg-dark-bg-deep p-8 rounded-[3rem] shadow-2xl overflow-hidden relative">
            <h4
                class="text-[10px] font-black text-brand-400 uppercase tracking-widest mb-10 px-2 flex items-center gap-2">
                <span class="w-2 h-2 bg-brand-500 rounded-full animate-pulse"></span>
                Program Enrollment Intensity Matrix
            </h4>
            <div class="h-80 w-full">
                <canvas id="chartProgramFocus"
                    data-labels="{{ json_encode(collect(data_get($data, 'by_course'))->pluck('code')) }}"
                    data-values="{{ json_encode(collect(data_get($data, 'by_course'))->pluck('alumni_count')) }}"></canvas>
            </div>
        </div>
    </div>

    <!-- LABOR ANALYTICS FOCUS -->
    <div x-show="subTab === 'labor'" class="space-y-8 animate-in fade-in duration-500" x-data="{ 
            fieldPage: 1, 
            fieldPerPage: 8,
            get fieldTotal() { return {{ count(data_get($data, 'top_fields', [])) }} },
            get fieldTotalPages() { return Math.ceil(this.fieldTotal / this.fieldPerPage) },
            get paginatedFields() {
                const data = {{ json_encode(data_get($data, 'top_fields', [])) }};
                return data.slice((this.fieldPage - 1) * this.fieldPerPage, this.fieldPage * this.fieldPerPage);
            }
        }">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <div
                class="bg-indigo-50 dark:bg-indigo-900/10 p-8 rounded-[2.5rem] border border-indigo-100 dark:border-indigo-900/30">
                <h4
                    class="text-xs font-black text-indigo-900 dark:text-indigo-300 mb-6 uppercase tracking-tight flex items-center gap-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                    Geographic Reach
                </h4>
                <div class="h-48 w-full">
                    <canvas id="chartLocationGrouped"
                        data-labels="{{ json_encode(collect(data_get($data, 'location_matrix'))->pluck('program')) }}"
                        data-local="{{ json_encode(collect(data_get($data, 'location_matrix'))->pluck('Local')) }}"
                        data-overseas="{{ json_encode(collect(data_get($data, 'location_matrix'))->pluck('Overseas')) }}"></canvas>
                </div>
            </div>

            <div
                class="bg-purple-50 dark:bg-purple-900/10 p-8 rounded-[2.5rem] border border-purple-100 dark:border-purple-900/30">
                <h4
                    class="text-xs font-black text-purple-900 dark:text-purple-300 mb-6 uppercase tracking-tight flex items-center gap-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4" />
                    </svg>
                    Sector Distribution
                </h4>
                <div class="h-48 w-full">
                    <canvas id="chartEstablishmentGrouped"
                        data-labels="{{ json_encode(collect(data_get($data, 'establishment_matrix'))->pluck('program')) }}"
                        data-public="{{ json_encode(collect(data_get($data, 'establishment_matrix'))->pluck('Public')) }}"
                        data-private="{{ json_encode(collect(data_get($data, 'establishment_matrix'))->pluck('Private')) }}"></canvas>
                </div>
            </div>

            <div
                class="bg-amber-50 dark:bg-amber-900/10 p-8 rounded-[2.5rem] border border-amber-100 dark:border-amber-900/30">
                <h4
                    class="text-xs font-black text-amber-900 dark:text-amber-300 mb-6 uppercase tracking-tight flex items-center gap-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6V4a2 2 0 00-2-2h-4a2 2 0 00-2 2v2m4 6h.01M5 20h14a2 2 0 002-2V8a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                    Industry Pulse
                </h4>
                <div class="h-48 w-full">
                    <canvas id="chartTopFieldsFocus"
                        data-labels="{{ json_encode(collect(data_get($data, 'top_fields'))->pluck('field_of_work')) }}"
                        data-values="{{ json_encode(collect(data_get($data, 'top_fields'))->pluck('count')) }}"></canvas>
                </div>
            </div>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div
                class="bg-white dark:bg-dark-bg-elevated p-8 rounded-[2.5rem] border border-gray-100 dark:border-dark-border shadow-sm">
                <div class="flex items-center justify-between mb-8">
                    <h4
                        class="text-xs font-black text-gray-900 dark:text-dark-text-primary uppercase tracking-widest px-2">
                        Professional Field Hubs
                    </h4>
                    <span
                        class="text-[9px] font-black text-amber-600 bg-amber-50 dark:bg-amber-900/30 px-3 py-1 rounded-full uppercase"
                        x-text="fieldTotal + ' Clusters'"></span>
                </div>

                <div class="overflow-hidden">
                    <table class="w-full text-left">
                        <thead>
                            <tr
                                class="text-[8px] font-black text-gray-400 uppercase tracking-[0.2em] border-b dark:border-dark-border">
                                <th class="pb-4 px-2">Field of Work</th>
                                <th class="pb-4 px-2 text-right">Verified Alumni</th>
                            </tr>
                        </thead>
                        <tbody class="text-[11px]">
                            <template x-for="field in paginatedFields" :key="field.field_of_work">
                                <tr
                                    class="hover:bg-gray-50/50 dark:hover:bg-dark-state-hover transition-colors border-b border-gray-50 dark:border-dark-border last:border-0">
                                    <td class="py-4 px-2 font-black text-gray-700 dark:text-dark-text-secondary uppercase"
                                        x-text="field.field_of_work"></td>
                                    <td class="py-4 px-2 text-right">
                                        <span class="font-black text-gray-900 dark:text-dark-text-primary"
                                            x-text="field.count"></span>
                                    </td>
                                </tr>
                            </template>
                        </tbody>
                    </table>
                </div>

                <div class="mt-6 flex items-center justify-center gap-4" x-show="fieldTotalPages > 1">
                    <button @click="fieldPage--" :disabled="fieldPage === 1"
                        class="p-2 rounded-xl bg-gray-50 dark:bg-dark-bg-subtle hover:bg-gray-100 dark:hover:bg-dark-state-hover disabled:opacity-30 transition-all font-black">
                        &larr;
                    </button>
                    <div class="flex gap-1">
                        <template x-for="i in fieldTotalPages" :key="i">
                            <button @click="fieldPage = i" class="w-2 h-2 rounded-full transition-all duration-300"
                                :class="fieldPage === i ? 'bg-amber-500 w-4' : 'bg-gray-200 dark:bg-dark-border'"></button>
                        </template>
                    </div>
                    <button @click="fieldPage++" :disabled="fieldPage === fieldTotalPages"
                        class="p-2 rounded-xl bg-gray-50 dark:bg-dark-bg-subtle hover:bg-gray-100 dark:hover:bg-dark-state-hover disabled:opacity-30 transition-all font-black">
                        &rarr;
                    </button>
                </div>
            </div>

            <div
                class="bg-gray-50 dark:bg-dark-bg-subtle/50 p-8 rounded-[2.5rem] border border-gray-100 dark:border-dark-border text-center">
                <h4 class="text-xs font-black text-gray-900 dark:text-dark-text-primary mb-8 uppercase tracking-tight">
                    Employment Status Concentration</h4>
                <div class="h-64 w-full">
                    <canvas id="chartLaborFocus"
                        data-labels="{{ json_encode(collect(data_get($data, 'by_employment'))->pluck('employment_status')) }}"
                        data-values="{{ json_encode(collect(data_get($data, 'by_employment'))->pluck('count')) }}"></canvas>
                </div>
            </div>
        </div>
    </div>

    <!-- DEMOGRAPHICS FOCUS -->
    <div x-show="subTab === 'demographics'" class="animate-in fade-in duration-500 space-y-8">
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
            <div
                class="bg-white dark:bg-dark-bg-elevated p-8 rounded-[3rem] border border-gray-100 dark:border-dark-border shadow-sm">
                <h4
                    class="text-xs font-black text-gray-400 dark:text-dark-text-muted mb-8 uppercase tracking-[0.2em] text-center">
                    Gender Demographics</h4>
                <div class="h-[300px] w-full relative">
                    <canvas id="chartGenderFocus"
                        data-labels="{{ json_encode(collect(data_get($data, 'by_gender'))->pluck('gender')) }}"
                        data-values="{{ json_encode(collect(data_get($data, 'by_gender'))->pluck('count')) }}"></canvas>
                </div>
            </div>

            <div
                class="bg-white dark:bg-dark-bg-elevated p-8 rounded-[3rem] border border-gray-100 dark:border-dark-border shadow-sm">
                <h4
                    class="text-xs font-black text-gray-400 dark:text-dark-text-muted mb-8 uppercase tracking-[0.2em] text-center">
                    Civil Status Matrix</h4>
                <div class="h-[300px] w-full relative">
                    <canvas id="chartCivilFocus"
                        data-labels="{{ json_encode(collect(data_get($data, 'by_civil_status'))->pluck('civil_status')) }}"
                        data-values="{{ json_encode(collect(data_get($data, 'by_civil_status'))->pluck('count')) }}"></canvas>
                </div>
            </div>
        </div>
    </div>
</div>