<div class="space-y-8">
    <!-- Report Official Header -->
    <div class="flex items-center justify-between pb-8 border-b-2 border-gray-900 dark:border-dark-border mb-8">
        <div class="flex items-center gap-4">
            <div class="w-12 h-12 bg-green-600 rounded-xl flex items-center justify-center text-white shadow-lg">
                <svg class="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04M12 2.944a11.955 11.955 0 018.618 3.04M12 21.189c4.736-2.559 8-7.429 8-12.429a11.955 11.955 0 01-8.618-3.04M12 21.189c-4.736-2.559-8-7.429-8-12.429a11.955 11.955 0 018.618-3.04" />
                </svg>
            </div>
            <div>
                <h1 class="text-xl font-black uppercase tracking-widest text-gray-900 dark:text-dark-text-primary">CHED Tracer Study</h1>
                <p class="text-[9px] font-bold text-gray-400 dark:text-dark-text-muted uppercase tracking-[0.2em] mt-0.5">Graduate Monitoring & Performance Record</p>
            </div>
        </div>
        <div class="text-right">
            <p class="text-[9px] font-black text-gray-400 dark:text-dark-text-muted uppercase tracking-widest leading-tight">Generated by: {{ Auth::user()->name }}</p>
            <p class="text-[9px] font-black text-brand-600 uppercase tracking-widest mt-1">{{ date('F d, Y • H:i') }}</p>
        </div>
    </div>

    <div class="overflow-x-auto">
        <table class="w-full border-collapse border border-gray-200 dark:border-dark-border">
            <thead class="bg-gray-100/50 dark:bg-dark-bg-subtle/50">
                <tr>
                    <th rowspan="2"
                        class="border border-gray-200 dark:border-dark-border px-4 py-4 text-[10px] font-black uppercase text-gray-600 dark:text-dark-text-muted">Alumni
                        Name</th>
                    <th rowspan="2"
                        class="border border-gray-200 dark:border-dark-border px-4 py-4 text-[10px] font-black uppercase text-gray-600 dark:text-dark-text-muted">Course &
                        Year</th>
                    <th colspan="3"
                        class="border border-gray-200 dark:border-dark-border px-4 py-2 text-[10px] font-black uppercase text-gray-600 dark:text-dark-text-muted text-center">
                        Employment Data</th>
                    <th rowspan="2"
                        class="border border-gray-200 dark:border-dark-border px-4 py-4 text-[10px] font-black uppercase text-gray-600 dark:text-dark-text-muted">Company
                        & Address</th>
                </tr>
                <tr>
                    <th
                        class="border border-gray-200 dark:border-dark-border px-3 py-2 text-[9px] font-black uppercase text-gray-500 dark:text-dark-text-muted text-center">
                        Status</th>
                    <th
                        class="border border-gray-200 dark:border-dark-border px-3 py-2 text-[9px] font-black uppercase text-gray-500 dark:text-dark-text-muted text-center">
                        Position</th>
                    <th
                        class="border border-gray-200 dark:border-dark-border px-3 py-2 text-[9px] font-black uppercase text-gray-500 dark:text-dark-text-muted text-center">
                        Salary (P)</th>
                </tr>
            </thead>
            <tbody class="dark:bg-dark-bg">
                @foreach($data as $profile)
                    <tr class="hover:bg-gray-50/50 dark:hover:bg-dark-state-hover transition-colors">
                        <td class="border border-gray-200 dark:border-dark-border px-4 py-3 text-xs font-bold text-gray-900 dark:text-dark-text-primary">
                            {{ $profile->last_name }}, {{ $profile->first_name }}</td>
                        <td class="border border-gray-200 dark:border-dark-border px-4 py-3 text-xs text-center">
                            <span class="font-black text-gray-900 dark:text-dark-text-primary">{{ $profile->course->code }}</span><br>
                            <span class="text-[10px] text-gray-400 dark:text-dark-text-muted">{{ $profile->batch_year }}</span>
                        </td>
                        <td class="border border-gray-200 dark:border-dark-border px-3 py-3 text-[10px] font-black text-center">
                            <span
                                class="{{ $profile->employment_status === 'Employed' ? 'text-green-600 dark:text-green-400' : 'text-amber-600 dark:text-amber-400' }}">{{ $profile->employment_status }}</span>
                        </td>
                        <td class="border border-gray-200 dark:border-dark-border px-3 py-3 text-[10px] font-bold text-center text-gray-700 dark:text-dark-text-secondary">
                            {{ $profile->position ?? 'N/A' }}</td>
                        <td class="border border-gray-200 dark:border-dark-border px-3 py-3 text-[10px] font-bold text-center text-gray-400 dark:text-dark-text-disabled italic">
                            Information Protected</td>
                        <td class="border border-gray-200 dark:border-dark-border px-4 py-3">
                            <div class="text-[10px] font-black text-gray-900 dark:text-dark-text-primary uppercase leading-tight">
                                {{ $profile->company_name ?? 'NOT REGISTERED' }}</div>
                            <div class="text-[9px] text-gray-400 dark:text-dark-text-muted italic leading-tight mt-1">
                                {{ $profile->work_address ?? 'N/A' }}</div>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="mt-20 pt-10 border-t flex justify-between items-start opacity-50 grayscale">
        <div class="text-center">
            <div class="w-48 border-b-2 border-gray-900 mb-2"></div>
            <p class="text-[10px] font-black uppercase tracking-widest">Alumni Office Coordinator</p>
        </div>
        <div class="text-center">
            <div class="w-48 border-b-2 border-gray-900 mb-2"></div>
            <p class="text-[10px] font-black uppercase tracking-widest">VP for Academic Affairs</p>
        </div>
    </div>
</div>